using System;
using System.Collections.Generic;
using System.Text;

namespace UniRow.Library.Models.Logmonitor
{
    /// <summary>
    /// Simple Logmonitor goes instead of the other logmonitors defined in this folder if the user chooses it. 
    /// Copyright 2015-2021 Bjarne Pedersen - "bp(a)zesttolife.dk"
    /// </summary>
    class SimpleLogMonitor
    {
        /// <summary>
        /// Autogenerated ID for the trainingslog
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// Username of the user which made the traininglog
        /// </summary>
        public string Username { get; set; }
        /// <summary>
        /// The date of the trainingpiece.
        /// </summary>
        public DateTime LogDate { get; set; }
        /// <summary>
        /// 1-5 rating of the Physical Experience of the training-piece
        /// </summary>
        public int PhysicalExperience { get; set; }
        /// <summary>
        /// 1-5 rating of the Psysical Experience of the training-piece
        /// </summary>
        public int PsysicalExperience { get; set; }
        /// <summary>
        /// Thoughts about the "Fight><Flee" experience the rowers might have
        /// </summary>
        public string FleeFightExperiences { get; set; }
        /// <summary>
        /// Possibility for the rowers to write the content of todays programme, so they later can see what they did.
        /// </summary>
        public string TodaysProgramme { get; set; }
        /// <summary>
        /// Possibility to write which pace/efford level they were doing for the piece aswell as average heartrate for the piece.
        /// </summary>
        public string PaceGuideAndAvgsplit { get; set; }
        /// <summary>
        /// Other factors which might affect the training of the day including stress, deaths amoung family or friends, meals ...
        /// </summary>
        public string OtherFactors { get; set; }
    }
}
